### PR TITLE
Fix: add user-agent to crates.io requests

### LINKED ISSUE #1: broken?!
As of June 15, this workflow doesn't work anymore.

running the cli returns an empty list of `<items>`

### PR DESCRIPTION
**Pull request by spamwax**
- Fixes #1 based on suggestion from [robjtede](https://github.com/FGRibreau/alfred-crates/issues/1#issuecomment-503506048) @robjtede
- Adds support for json & xml output (Alfred 3, 4 vs Alfred 1 and 2)

Uses two new crates:
- `curl` to fix user-agent issue
- `alfred` to support different versions of Alfred

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -14,34 +16,56 @@ fn main() {
...
-        .arg(Arg::with_name("query")
-            .short("q")
-            .required(true)
-            .index(1))
+        .arg(Arg::with_name("query").short("q").required(true).index(1))
         .get_matches();
 
+    let mut easy_client = Easy::new();
+    easy_client
+        .useragent("Alfred Crates (robjtede fork)")
```
Comment (robjtede) [inline src/main.rs]: lol, please dont leave this user agent in as it is

```suggestion
        .useragent(format!("{} (v{})", env!("CARGO_PKG_name"), env!("CARGO_PKG_VERSION")))
```

Comment (spamwax) [reply src/main.rs]: Updated in a new commit.

**Comment by FGRibreau** [comment]
Thanks! And sorry for the delay to merge this :)
